---
- name: task inclusion
  hosts: all
  gather_facts: false

  tasks:
    - include: files.yml
      vars:
        path: "/tmp/foo"
        file: "herp"

    - include: files.yml
      vars:
        path: "/tmp/foo"
        file: "derp"
